# Required top-level events configuration
events {}

# HTTPS configuration
http {
	server {
		# Listen on port 443 inside the container for openssl
		listen 443 ssl;

		server_name ivmirand.42.fr;

		ssl_protocols TLSv1.2 TLSv1.3;

		ssl_certificate			/etc/nginx/ssl/nginx.crt;
		ssl_certificate_key		/etc/nginx/ssl/nginx.key;

		location / {
			# Return a plain-text response for every request
			return 200 "NGINX HTTPS OK\n";
		}
	}
}
